export enum Actions {
  SELECT_FILE = 'SELECT_FILE',
  GRAYSCALE = 'GRAYSCALE',
  INVERT = 'INVERT',
  SHARPEN = 'SHARPEN',
  SEPIA = 'SEPIA',
  VIGNETTE = 'VIGNETTE',
  LIGHT_LEAKS = 'LIGHT_LEAKS',
  BLUR = 'BLUR',
  NOISE = 'NOISE',
  FRAGMENT = 'FRAGMENT',
  CROP_CIRCLE = 'CROP_CIRCLE',
}
